#!/usr/bin/env python3
"""estimating_rollup.py — aggregate Task Durations actuals across all heater
cards into 04-knowledge/estimating-actuals-rollup.md.

This is the vault's return path for job data: every completed job's actuals,
side by side with the estimating benchmarks (100 ft/hr pigging, 6 hr rig-in,
6 hr rig-out), so estimates calibrate against reality as the dataset grows.

REFERENCE ONLY — this report never changes a rate or a skill value. Estimating
benchmark changes are Lane 4: Jesse decides, then usadebusk-estimating is
edited in the config repo.

Pure standard library. Writes a GENERATED file.

Usage:
    python tools/estimating_rollup.py           write the rollup
    python tools/estimating_rollup.py --print   also print to stdout

Windows: `py -3 tools/estimating_rollup.py`.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

OUT_REL = "04-knowledge/estimating-actuals-rollup.md"
FACILITIES = "02-facilities"

# Benchmarks as currently stated in usadebusk-estimating (Duration Model).
BENCH_FT_PER_HR = 100.0
BENCH_RIG_IN = 6.0
BENCH_RIG_OUT = 6.0

TD_COLS = ["Date", "Job #", "Rigs", "Rig-In", "Pig", "Smart Pig",
           "Rig-Over", "Rig-Out", "Stand-By", "Total"]


def parse_frontmatter(text: str) -> dict[str, str]:
    fm: dict[str, str] = {}
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return fm
    for line in lines[1:]:
        if line.strip() == "---":
            break
        m = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if m:
            fm[m.group(1).strip()] = m.group(2).strip().strip("'\"")
    return fm


def section_lines(text: str, heading: str) -> list[str]:
    """Lines of the section starting at `## {heading}` up to the next ## heading."""
    out: list[str] = []
    in_section = False
    for line in text.splitlines():
        if re.match(rf"^##\s+.*{re.escape(heading)}", line):
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if in_section:
            out.append(line)
    return out


def table_rows(lines: list[str]) -> list[list[str]]:
    """Data rows of the first markdown table in `lines` (header + separator skipped)."""
    rows: list[list[str]] = []
    seen_header = False
    for line in lines:
        s = line.strip()
        if not s.startswith("|"):
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        if not seen_header:
            seen_header = True  # header row
            continue
        if all(re.fullmatch(r":?-{2,}:?", c or "") for c in cells):
            continue  # separator row
        if any(c for c in cells):
            rows.append(cells)
    return rows


def num(cell: str | None) -> float | None:
    """Tolerant numeric parse: '~385.8' -> 385.8; '?', '-', '(not verified)' -> None."""
    if cell is None:
        return None
    s = cell.strip().lstrip("~").replace(",", "")
    m = re.match(r"^-?\d+(\.\d+)?", s)
    return float(m.group(0)) if m else None


def heater_cards(root: Path):
    for p in sorted((root / FACILITIES).rglob("*.md")):
        if p.name.startswith("_"):
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        fm = parse_frontmatter(text)
        if fm.get("type") == "heater":
            yield p, fm, text


def heater_total_footage(text: str) -> float | None:
    """Sum the numeric Total Length values of 'Heater total' rows in Config Rollup."""
    total = 0.0
    found = False
    for row in table_rows(section_lines(text, "Config Rollup")):
        if row and row[0].strip().lower() == "heater total" and len(row) >= 5:
            v = num(row[4])
            if v is not None:
                total += v
                found = True
    return total if found else None


def build(root: Path) -> str:
    actual_rows = []
    gaps = []
    for path, fm, text in heater_cards(root):
        tag = fm.get("heater-tag") or path.stem
        client = fm.get("client", "?")
        footage = heater_total_footage(text)
        rows = table_rows(section_lines(text, "Task Durations"))
        if not rows:
            gaps.append(f"{tag} ({client}) — no Task Durations actuals yet")
            continue
        for r in rows:
            r = (r + [""] * len(TD_COLS))[:len(TD_COLS)]
            pig = num(r[4])
            fthr = None
            if pig and footage:
                fthr = footage / pig
            actual_rows.append((tag, client, r, footage, fthr))

    lines = [
        "<!-- GENERATED by tools/estimating_rollup.py - do not edit; rerun to refresh. -->",
        "# Estimating Actuals Rollup",
        f"**Generated:** {date.today().isoformat()} — all Task Durations actuals across "
        "heater cards, against the estimating benchmarks. Reference only: benchmark or "
        "rate changes are Lane 4 (Jesse decides; `usadebusk-estimating` is then edited "
        "in the config repo).",
        "",
        f"Benchmarks as stated in `usadebusk-estimating`: **{BENCH_FT_PER_HR:.0f} ft/hr** "
        f"pigging (nominal fouling), **{BENCH_RIG_IN:.0f} hr** rig-in / "
        f"**{BENCH_RIG_OUT:.0f} hr** rig-out proposal defaults.",
        "",
        "> Interpretation caution: task hours are ELAPSED wall-clock (per the canonical "
        "card schema), and ft/elapsed-hr divides heater-total footage by elapsed Pig "
        "hours — it does not normalize for rig count or passes cleaned in parallel. "
        "Compare jobs with the Rigs column in view.",
        "",
        "## Actuals",
        "",
        "| Heater | Client | Date | Job # | Rigs | Rig-In | Pig | Smart Pig | Rig-Out | "
        "Stand-By | Total | Heater footage (ft) | ft / elapsed pig-hr |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    if not actual_rows:
        lines.append("| _no actuals recorded yet_ | | | | | | | | | | | | |")
    for tag, client, r, footage, fthr in actual_rows:
        foot_s = f"{footage:,.0f}" if footage else "(not recorded)"
        fthr_s = f"{fthr:.0f}" if fthr else "-"
        lines.append(
            f"| {tag} | {client} | {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]} | {r[5]} | "
            f"{r[7]} | {r[8]} | {r[9]} | {foot_s} | {fthr_s} |")
    lines += [
        "",
        "## Coverage gaps",
        "",
    ]
    lines += [f"- {g}" for g in gaps] or ["- none — every card carries actuals"]
    lines += [
        "",
        "## Reading this",
        "",
        f"- With **{len(actual_rows)}** actual job row(s), this is a growing dataset, not a "
        "calibrated model. Treat per-job ft/hr as anecdotes until several same-service "
        "jobs accumulate.",
        "- Rig-In/Rig-Out actuals well off the "
        f"{BENCH_RIG_IN:.0f}/{BENCH_RIG_OUT:.0f} hr defaults, or ft/hr consistently off "
        f"{BENCH_FT_PER_HR:.0f}, are the signal to revisit the Duration Model — raise it "
        "with Jesse rather than editing the skill from here.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=None)
    ap.add_argument("--print", action="store_true", dest="do_print")
    args = ap.parse_args()

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    root = (args.root or Path(__file__).resolve().parent.parent).resolve()
    if not (root / "CLAUDE.md").exists():
        print(f"ERROR: {root} does not look like the vault root (no CLAUDE.md).")
        return 1

    content = build(root)
    out = root / OUT_REL
    out.write_text(content, encoding="utf-8")
    print(f"Wrote {out}")
    if args.do_print:
        print("\n" + content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
