#!/usr/bin/env python3
"""vault_index.py — generate INDEX.md, one line per note, so every session
can know what the vault contains without loading it.

Pure standard library. Writes a GENERATED file (first-line marker) so
vault_lint excludes it as a link source — a generated index can never
satisfy the ORPHAN check; only real links from real notes do.

Scope: knowledge-bearing layers only. Excluded: 00-inbox (transient),
50-dashboards (generated), archive/templates/tools/.obsidian/.git.

Usage:
    python tools/vault_index.py           write INDEX.md
    python tools/vault_index.py --print   also print to stdout

Windows: `py -3 tools/vault_index.py`.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

INDEX_REL = "INDEX.md"

# (top-level dir, section heading) in display order.
SECTIONS = [
    ("01-context", "Context (auto-loaded every session)"),
    ("02-facilities", "Facilities & Heater Cards"),
    ("04-knowledge", "Knowledge"),
    ("06-reviews", "Reviews"),
    ("07-llms", "LLMs"),
    ("08-systems", "Systems"),
    ("09-interests", "Interests"),
    # `apps` added 2026-08-24. It was in neither map — not here, not in the vault
    # CLAUDE.md — the same condition that let 06-insights drift for seven weeks.
    # Registering it alone was not enough: every .md under apps/ was a README and
    # SKIP_NAMES drops those, so the section rendered empty. The two tools now
    # carry real notes; the folder READMEs stay READMEs.
    ("apps", "Apps & Artifacts"),
]

SKIP_NAMES = {"README.md"}
GENERATED_MARKER = "GENERATED by tools/"
HEADING_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)
FM_TITLE_RE = re.compile(r"^title:\s*(.+)$", re.MULTILINE)


def note_title(text: str, stem: str) -> str:
    lines = text.splitlines()
    # Skip leading blank lines and full-line HTML comments (loop markers) so a
    # marked note's `title:` is still read; see frontmatter_start() in vault_lint.py.
    fm_at = None
    for i, line in enumerate(lines):
        s = line.strip()
        if not s or (s.startswith("<!--") and s.endswith("-->")):
            continue
        fm_at = i if s == "---" else None
        break
    if fm_at is not None:
        try:
            end = lines[fm_at + 1:].index("---") + fm_at + 1
            fm = "\n".join(lines[fm_at + 1:end])
            m = FM_TITLE_RE.search(fm)
            if m:
                return m.group(1).strip().strip("'\"")
        except ValueError:
            pass
    m = HEADING_RE.search(text)
    if m:
        return m.group(1).strip()
    return stem


def build(root: Path) -> str:
    lines = [
        "<!-- GENERATED by tools/vault_index.py - do not edit; rerun to refresh. -->",
        "# Vault Index",
        f"**Generated:** {date.today().isoformat()} — one line per note. "
        "Regenerated by the capture and consolidation loops.",
        "",
    ]

    # Vault-wide stem counts: Obsidian resolves a bare [[stem]] link
    # ambiguously when multiple files share a basename (e.g. several
    # per-tool overview.md files), silently opening the wrong note. Any
    # stem that collides gets a path-qualified link instead.
    all_paths = []
    for top, _ in SECTIONS:
        d = root / top
        if d.is_dir():
            all_paths.extend(p for p in d.rglob("*.md") if p.name not in SKIP_NAMES)
    stem_counts: dict[str, int] = {}
    for p in all_paths:
        stem_counts[p.stem] = stem_counts.get(p.stem, 0) + 1

    for top, heading in SECTIONS:
        d = root / top
        if not d.is_dir():
            continue
        entries = []
        for p in sorted(d.rglob("*.md")):
            if p.name in SKIP_NAMES:
                continue
            try:
                text = p.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if GENERATED_MARKER in text[:200]:
                continue
            title = note_title(text, p.stem)
            sub = p.parent.relative_to(d).as_posix()
            loc = f" `({sub})`" if sub != "." else ""
            if stem_counts[p.stem] > 1:
                target = p.relative_to(root).with_suffix("").as_posix()
                link = f"[[{target}|{p.stem}]]"
            else:
                link = f"[[{p.stem}]]"
            # Avoid "link — stem" noise when the title just repeats the filename.
            if title.lower() == p.stem.lower():
                entries.append(f"- {link}{loc}")
            else:
                entries.append(f"- {link} — {title}{loc}")
        if entries:
            lines += [f"## {heading}", ""] + entries + [""]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=None)
    ap.add_argument("--print", action="store_true", dest="do_print")
    args = ap.parse_args()

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    root = (args.root or Path(__file__).resolve().parent.parent).resolve()
    if not (root / "CLAUDE.md").exists():
        print(f"ERROR: {root} does not look like the vault root (no CLAUDE.md).")
        return 1

    content = build(root)
    out = root / INDEX_REL
    out.write_text(content, encoding="utf-8")
    print(f"Wrote {out} ({content.count(chr(10))} lines)")
    if args.do_print:
        print("\n" + content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
