#!/usr/bin/env python3
"""vault_index.py — generate INDEX.md, one line per note, so every session
can know what the vault contains without loading it.

Pure standard library. Writes a GENERATED file (first-line marker) so
vault_lint excludes it as a link source — a generated index can never
satisfy the ORPHAN check; only real links from real notes do.

Scope: knowledge-bearing layers only. Excluded: 00-inbox (transient),
50-dashboards (generated), archive/templates/tools/.obsidian/.git.

Usage:
    python tools/vault_index.py           write INDEX.md
    python tools/vault_index.py --print   also print to stdout

Windows: `py -3 tools/vault_index.py`.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

INDEX_REL = "INDEX.md"

# (top-level dir, section heading) in display order.
SECTIONS = [
    ("01-context", "Context (auto-loaded every session)"),
    ("02-facilities", "Facilities & Heater Cards"),
    ("04-knowledge", "Knowledge"),
    ("06-insights", "Insights & Reviews"),
    ("07-llms", "LLMs"),
    ("08-systems", "Systems"),
    ("09-interests", "Interests"),
]

SKIP_NAMES = {"README.md"}
GENERATED_MARKER = "GENERATED by tools/"
HEADING_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)
FM_TITLE_RE = re.compile(r"^title:\s*(.+)$", re.MULTILINE)


def note_title(text: str, stem: str) -> str:
    lines = text.splitlines()
    if lines and lines[0].strip() == "---":
        try:
            end = lines[1:].index("---") + 1
            fm = "\n".join(lines[1:end])
            m = FM_TITLE_RE.search(fm)
            if m:
                return m.group(1).strip().strip("'\"")
        except ValueError:
            pass
    m = HEADING_RE.search(text)
    if m:
        return m.group(1).strip()
    return stem


def build(root: Path) -> str:
    lines = [
        "<!-- GENERATED by tools/vault_index.py - do not edit; rerun to refresh. -->",
        "# Vault Index",
        f"**Generated:** {date.today().isoformat()} — one line per note. "
        "Regenerated by the capture and consolidation loops.",
        "",
    ]
    for top, heading in SECTIONS:
        d = root / top
        if not d.is_dir():
            continue
        entries = []
        for p in sorted(d.rglob("*.md")):
            if p.name in SKIP_NAMES:
                continue
            try:
                text = p.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if GENERATED_MARKER in text[:200]:
                continue
            title = note_title(text, p.stem)
            sub = p.parent.relative_to(d).as_posix()
            loc = f" `({sub})`" if sub != "." else ""
            # Avoid "[[stem]] — stem" noise when the title just repeats the filename.
            if title.lower() == p.stem.lower():
                entries.append(f"- [[{p.stem}]]{loc}")
            else:
                entries.append(f"- [[{p.stem}]] — {title}{loc}")
        if entries:
            lines += [f"## {heading}", ""] + entries + [""]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=None)
    ap.add_argument("--print", action="store_true", dest="do_print")
    args = ap.parse_args()

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    root = (args.root or Path(__file__).resolve().parent.parent).resolve()
    if not (root / "CLAUDE.md").exists():
        print(f"ERROR: {root} does not look like the vault root (no CLAUDE.md).")
        return 1

    content = build(root)
    out = root / INDEX_REL
    out.write_text(content, encoding="utf-8")
    print(f"Wrote {out} ({content.count(chr(10))} lines)")
    if args.do_print:
        print("\n" + content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
