#!/usr/bin/env python3
"""vault_health.py — generate 50-dashboards/health.md, the vault's vitals.

Pure standard library; reuses tools/vault_lint.py for the lint counts. Writes
a GENERATED file that overwrites itself on every run and says so in its header.
Generated files are the one sanctioned exception to the vault's append-only
discipline.

What it trends (the numbers you can act on in one glance):
    - open decision rows        (from 50-dashboards/decision-queue.md)
    - review notes awaiting a decision (unchecked Decision boxes in 06-insights)
    - inbox items + median age  (git commit dates)
    - lint errors / warnings    (tools/vault_lint.py)
    - days since last commit    (basic liveness signal)
    - per-loop heartbeats       (commit-subject prefixes, flagged at >2x cadence)

Usage:
    python tools/vault_health.py            write 50-dashboards/health.md
    python tools/vault_health.py --print     also print the dashboard to stdout

Windows: `py tools/vault_health.py`.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import date, datetime
from pathlib import Path
from statistics import median

sys.path.insert(0, str(Path(__file__).resolve().parent))
import vault_lint  # noqa: E402  (same-dir sibling module)

QUEUE_REL = "50-dashboards/decision-queue.md"
HEALTH_REL = "50-dashboards/health.md"
QUEUE_ROW_RE = re.compile(r"^\|\s*(DQ-\d+)\s*\|")
INBOX_SKIP_SUBDIRS = ("preserved-dsps",)

# Loop heartbeats: (label, commit-subject prefix, cadence_days, scheduled).
# Each loop's closing commit is its heartbeat. A *scheduled* loop is flagged
# overdue (red) when its last heartbeat is older than 2x its cadence, or never
# fired. A non-scheduled loop is run on-demand — it shows its last run for
# information only and never goes red. The review/agent loop is on-demand by
# design and not listed at all.
LOOP_HEARTBEATS = [
    ("Capture loop", "vault-capture:", 7, True),
    # Idea loop runs nightly but only commits when a seed exists, so its
    # heartbeat cadence is monitoring-grade (30 d), not its run cadence:
    # FAIL here means either the scheduler died or the seed queue has been
    # empty for 60+ days — both worth a look, neither an emergency.
    ("Idea-research loop", "vault-idea-research:", 30, True),
    ("Skill-drift loop", "skill-drift:", 31, True),
    ("Consolidation loop", "vault-consolidate:", 31, True),
]


def git_last_commit_date(root: Path, rel: str) -> date | None:
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", rel],
            cwd=root, capture_output=True, text=True, timeout=30,
        ).stdout.strip()
        return datetime.strptime(out, "%Y-%m-%d").date() if out else None
    except Exception:
        return None


def count_open_decisions(root: Path) -> int:
    q = root / QUEUE_REL
    if not q.is_file():
        return 0
    open_rows = 0
    in_open = False
    for line in q.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s.startswith("## Open"):
            in_open = True
            continue
        if in_open and s.startswith("## "):
            break
        if in_open and QUEUE_ROW_RE.match(line):
            open_rows += 1
    return open_rows


def count_pending_reviews(root: Path) -> int:
    """Review notes in 06-insights with at least one unchecked Decision box.

    This is the 'what needs Jesse' number: loops write review notes with
    empty checkboxes, and an unreviewed pile is where compounding stalls.
    Surfaced at session startup via CLAUDE.md's health-check rule.
    """
    insights = root / "06-insights"
    if not insights.is_dir():
        return 0
    pending = 0
    for p in sorted(insights.glob("*.md")):
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if "GENERATED by tools/" in text[:200]:
            continue
        # A note with a terminal status is resolved — its leftover unchecked
        # boxes (rejected alternatives) are not pending work. Skip it.
        if vault_lint.parse_frontmatter(text).get("status") in vault_lint.TERMINAL_STATUS:
            continue
        # Only count notes that have a Decision section with an unchecked box.
        if re.search(r"^#+\s*Decision\b", text, re.MULTILINE) and re.search(r"^\s*-\s*\[ \]", text, re.MULTILINE):
            pending += 1
    return pending


def inbox_stats(root: Path) -> tuple[int, int | None, int | None]:
    """Return (item_count, median_age_days, max_age_days) for inbox files."""
    inbox = root / vault_lint.INBOX_DIR
    if not inbox.is_dir():
        return 0, None, None
    today = date.today()
    ages: list[int] = []
    count = 0
    for p in sorted(inbox.rglob("*")):
        if not p.is_file() or p.name.startswith("."):
            continue
        rel = p.relative_to(inbox).as_posix()
        if any(rel.startswith(s + "/") for s in INBOX_SKIP_SUBDIRS):
            continue
        count += 1
        d = git_last_commit_date(root, str(p.relative_to(root)))
        if d is not None:
            ages.append((today - d).days)
    if not ages:
        return count, None, None
    return count, int(median(ages)), max(ages)


def days_since_last_commit(root: Path) -> int | None:
    d = git_last_commit_date(root, ".")
    return (date.today() - d).days if d else None


def git_last_grep_date(root: Path, prefix: str) -> date | None:
    """Date of the most recent commit whose subject starts with `prefix`."""
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", f"--grep=^{re.escape(prefix)}"],
            cwd=root, capture_output=True, text=True, timeout=30,
        ).stdout.strip()
        return datetime.strptime(out, "%Y-%m-%d").date() if out else None
    except Exception:
        return None


def loop_heartbeats(root: Path):
    """Return (rows, any_overdue). Each row: (label, last_seen, cadence, status)."""
    today = date.today()
    rows = []
    any_overdue = False
    for label, prefix, cadence, scheduled in LOOP_HEARTBEATS:
        d = git_last_grep_date(root, prefix)
        last = "never fired" if d is None else f"{d.isoformat()} ({(today - d).days} d ago)"
        if not scheduled:
            # on-demand: informational only, never red
            rows.append((label, last, "on-demand", "manual"))
            continue
        if d is None:
            # scheduled but no heartbeat yet: "overdue" needs a prior beat to
            # measure against, so a never-fired scheduled loop is pending, not dead.
            rows.append((label, "awaiting 1st run", f"{cadence} d", "pending"))
        else:
            overdue = (today - d).days > 2 * cadence
            rows.append((label, last, f"{cadence} d", "FAIL" if overdue else "ok"))
            any_overdue = any_overdue or overdue
    return rows, any_overdue


def build(root: Path) -> str:
    findings = vault_lint.run_lint(root)
    errors = sum(1 for f in findings if f.severity == "error")
    warnings = len(findings) - errors

    open_dec = count_open_decisions(root)
    pending_rev = count_pending_reviews(root)
    inbox_n, inbox_med, inbox_max = inbox_stats(root)
    since = days_since_last_commit(root)
    hb_rows, hb_overdue = loop_heartbeats(root)

    def flag(ok: bool) -> str:
        return "ok" if ok else "FAIL"

    dash = "-"
    inbox_med_s = dash if inbox_med is None else f"{inbox_med} d"
    inbox_max_s = dash if inbox_max is None else f"{inbox_max} d"
    since_s = dash if since is None else f"{since} d"

    lines = [
        "<!-- GENERATED by tools/vault_health.py - do not edit; rerun to refresh -->",
        "# Vault Health",
        f"**Generated:** {date.today().isoformat()}",
        "",
        "| Metric | Value | Target | Status |",
        "|---|---|---|---|",
        f"| Open decision rows | {open_dec} | <= 10 | {flag(open_dec <= 10)} |",
        f"| Review notes awaiting decision | {pending_rev} | <= 5 | {flag(pending_rev <= 5)} |",
        f"| Lint errors | {errors} | 0 | {flag(errors == 0)} |",
        f"| Lint warnings | {warnings} | (backlog) | {flag(True)} |",
        f"| Inbox items | {inbox_n} | {dash} | {flag(True)} |",
        f"| Inbox median age | {inbox_med_s} | < 14 d | {flag(inbox_med is None or inbox_med < 14)} |",
        f"| Inbox oldest item | {inbox_max_s} | < 30 d | {flag(inbox_max is None or inbox_max < 30)} |",
        f"| Days since last commit | {since_s} | {dash} | {flag(True)} |",
        f"| Loop heartbeats overdue | {'yes' if hb_overdue else 'no'} | no | {flag(not hb_overdue)} |",
        "",
        "## Loop heartbeats",
        "",
        "Each scheduled loop's closing commit is its heartbeat. A scheduled loop goes **FAIL** "
        "when its last heartbeat is older than 2x cadence; **pending** = scheduled but not yet "
        "run; **manual** = on-demand, not scheduled. The review/agent loop is on-demand by "
        "design and not listed.",
        "",
        "| Loop | Last heartbeat | Cadence | Status |",
        "|---|---|---|---|",
    ]
    lines += [f"| {label} | {last} | {cad} | {st} |" for label, last, cad, st in hb_rows]
    lines += [
        "",
        "## Notes",
        "",
        f"- **Decision queue:** [[decision-queue]] — {open_dec} open. Cap is 10; "
        "over cap, proposal-generating loops pause.",
        f"- **Review notes awaiting decision:** {pending_rev} in `06-insights/` with unchecked "
        "Decision boxes. Any session that sees this above 0 should offer to walk through them — "
        "unreviewed proposals are where compounding stalls.",
        "- **Lint warnings** are the standing to-do list (provenance-frontmatter backfill, "
        "stale `related:` links), not failures. Detail: run `python tools/vault_lint.py --report` "
        "→ `50-dashboards/lint-report.md`.",
        "- **Heartbeats overdue** means a scheduled loop hasn't committed within 2x its cadence — "
        "check whether its desktop scheduled task is still firing (sleep, app closed, or "
        "deregistration are the usual causes).",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=None)
    ap.add_argument("--print", action="store_true", dest="do_print")
    args = ap.parse_args()

    try:  # keep --print from dying on a legacy Windows console codepage
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    root = (args.root or Path(__file__).resolve().parent.parent).resolve()
    if not (root / "CLAUDE.md").exists():
        print(f"ERROR: {root} does not look like the vault root (no CLAUDE.md).")
        return 1

    content = build(root)
    out = root / HEALTH_REL
    out.parent.mkdir(exist_ok=True)
    out.write_text(content, encoding="utf-8")
    print(f"Wrote {out}")
    if args.do_print:
        print("\n" + content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
